/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaiterRouteImport } from './routes/waiter'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ConsumerRouteImport } from './routes/consumer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as ManagerCentralRouteImport } from './routes/manager.central'
import { Route as ManagerAddRouteImport } from './routes/manager.add'
import { Route as ManagerUnitTypeIdRouteImport } from './routes/manager.unit.$type.$id'

const WaiterRoute = WaiterRouteImport.update({
  id: '/waiter',
  path: '/waiter',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/consumer',
  path: '/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerCentralRoute = ManagerCentralRouteImport.update({
  id: '/manager/central',
  path: '/manager/central',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAddRoute = ManagerAddRouteImport.update({
  id: '/manager/add',
  path: '/manager/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUnitTypeIdRoute = ManagerUnitTypeIdRouteImport.update({
  id: '/manager/unit/$type/$id',
  path: '/manager/unit/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consumer': typeof ConsumerRoute
  '/landing': typeof LandingRoute
  '/waiter': typeof WaiterRoute
  '/manager/add': typeof ManagerAddRoute
  '/manager/central': typeof ManagerCentralRoute
  '/manager/': typeof ManagerIndexRoute
  '/manager/unit/$type/$id': typeof ManagerUnitTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consumer': typeof ConsumerRoute
  '/landing': typeof LandingRoute
  '/waiter': typeof WaiterRoute
  '/manager/add': typeof ManagerAddRoute
  '/manager/central': typeof ManagerCentralRoute
  '/manager': typeof ManagerIndexRoute
  '/manager/unit/$type/$id': typeof ManagerUnitTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consumer': typeof ConsumerRoute
  '/landing': typeof LandingRoute
  '/waiter': typeof WaiterRoute
  '/manager/add': typeof ManagerAddRoute
  '/manager/central': typeof ManagerCentralRoute
  '/manager/': typeof ManagerIndexRoute
  '/manager/unit/$type/$id': typeof ManagerUnitTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consumer'
    | '/landing'
    | '/waiter'
    | '/manager/add'
    | '/manager/central'
    | '/manager/'
    | '/manager/unit/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/consumer'
    | '/landing'
    | '/waiter'
    | '/manager/add'
    | '/manager/central'
    | '/manager'
    | '/manager/unit/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consumer'
    | '/landing'
    | '/waiter'
    | '/manager/add'
    | '/manager/central'
    | '/manager/'
    | '/manager/unit/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConsumerRoute: typeof ConsumerRoute
  LandingRoute: typeof LandingRoute
  WaiterRoute: typeof WaiterRoute
  ManagerAddRoute: typeof ManagerAddRoute
  ManagerCentralRoute: typeof ManagerCentralRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerUnitTypeIdRoute: typeof ManagerUnitTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiter': {
      id: '/waiter'
      path: '/waiter'
      fullPath: '/waiter'
      preLoaderRoute: typeof WaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer': {
      id: '/consumer'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/central': {
      id: '/manager/central'
      path: '/manager/central'
      fullPath: '/manager/central'
      preLoaderRoute: typeof ManagerCentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/add': {
      id: '/manager/add'
      path: '/manager/add'
      fullPath: '/manager/add'
      preLoaderRoute: typeof ManagerAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/unit/$type/$id': {
      id: '/manager/unit/$type/$id'
      path: '/manager/unit/$type/$id'
      fullPath: '/manager/unit/$type/$id'
      preLoaderRoute: typeof ManagerUnitTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConsumerRoute: ConsumerRoute,
  LandingRoute: LandingRoute,
  WaiterRoute: WaiterRoute,
  ManagerAddRoute: ManagerAddRoute,
  ManagerCentralRoute: ManagerCentralRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerUnitTypeIdRoute: ManagerUnitTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
