/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaiterRouteImport } from './routes/waiter'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ConsumerRouteImport } from './routes/consumer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as BusinessCentralRouteImport } from './routes/business.central'
import { Route as BusinessAddRouteImport } from './routes/business.add'
import { Route as BusinessUnitTypeIdRouteImport } from './routes/business.unit.$type.$id'

const WaiterRoute = WaiterRouteImport.update({
  id: '/waiter',
  path: '/waiter',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRoute = ConsumerRouteImport.update({
  id: '/consumer',
  path: '/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessCentralRoute = BusinessCentralRouteImport.update({
  id: '/business/central',
  path: '/business/central',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAddRoute = BusinessAddRouteImport.update({
  id: '/business/add',
  path: '/business/add',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessUnitTypeIdRoute = BusinessUnitTypeIdRouteImport.update({
  id: '/business/unit/$type/$id',
  path: '/business/unit/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consumer': typeof ConsumerRoute
  '/landing': typeof LandingRoute
  '/waiter': typeof WaiterRoute
  '/business/add': typeof BusinessAddRoute
  '/business/central': typeof BusinessCentralRoute
  '/business/': typeof BusinessIndexRoute
  '/business/unit/$type/$id': typeof BusinessUnitTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consumer': typeof ConsumerRoute
  '/landing': typeof LandingRoute
  '/waiter': typeof WaiterRoute
  '/business/add': typeof BusinessAddRoute
  '/business/central': typeof BusinessCentralRoute
  '/business': typeof BusinessIndexRoute
  '/business/unit/$type/$id': typeof BusinessUnitTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/consumer': typeof ConsumerRoute
  '/landing': typeof LandingRoute
  '/waiter': typeof WaiterRoute
  '/business/add': typeof BusinessAddRoute
  '/business/central': typeof BusinessCentralRoute
  '/business/': typeof BusinessIndexRoute
  '/business/unit/$type/$id': typeof BusinessUnitTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/consumer'
    | '/landing'
    | '/waiter'
    | '/business/add'
    | '/business/central'
    | '/business/'
    | '/business/unit/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/consumer'
    | '/landing'
    | '/waiter'
    | '/business/add'
    | '/business/central'
    | '/business'
    | '/business/unit/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/consumer'
    | '/landing'
    | '/waiter'
    | '/business/add'
    | '/business/central'
    | '/business/'
    | '/business/unit/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConsumerRoute: typeof ConsumerRoute
  LandingRoute: typeof LandingRoute
  WaiterRoute: typeof WaiterRoute
  BusinessAddRoute: typeof BusinessAddRoute
  BusinessCentralRoute: typeof BusinessCentralRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  BusinessUnitTypeIdRoute: typeof BusinessUnitTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiter': {
      id: '/waiter'
      path: '/waiter'
      fullPath: '/waiter'
      preLoaderRoute: typeof WaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer': {
      id: '/consumer'
      path: '/consumer'
      fullPath: '/consumer'
      preLoaderRoute: typeof ConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/central': {
      id: '/business/central'
      path: '/business/central'
      fullPath: '/business/central'
      preLoaderRoute: typeof BusinessCentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/add': {
      id: '/business/add'
      path: '/business/add'
      fullPath: '/business/add'
      preLoaderRoute: typeof BusinessAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/unit/$type/$id': {
      id: '/business/unit/$type/$id'
      path: '/business/unit/$type/$id'
      fullPath: '/business/unit/$type/$id'
      preLoaderRoute: typeof BusinessUnitTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConsumerRoute: ConsumerRoute,
  LandingRoute: LandingRoute,
  WaiterRoute: WaiterRoute,
  BusinessAddRoute: BusinessAddRoute,
  BusinessCentralRoute: BusinessCentralRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  BusinessUnitTypeIdRoute: BusinessUnitTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
